version: '3'

services:
  app:
    container_name: fastapi
    build: ./docker/fastapi
    volumes:
      - ./fastapi:/app
    ports:
      - "80:80"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80